version: "3.7"

networks:
  gochat-net: {}

services:
  postgres:
    container_name: gochat_postgres
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: .env
    networks:
      - gochat-net
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  adminer:
    container_name: gochat_adminer
    image: adminer
    networks:
      - gochat-net
    ports:
      - 8080:8080
  api:
    container_name: gochat_service_api
    restart: always
    build:
      dockerfile: ./platform/endpoints/api/Dockerfile
      context: .
    env_file: .env
    networks:
      - gochat-net
    ports:
      - ${API_SERVICE_PORT}:${API_SERVICE_PORT}
    depends_on:
      - postgres
    command: ./api
  ws:
    container_name: gochat_service_ws
    restart: always
    build:
      dockerfile: ./platform/endpoints/ws/Dockerfile
      context: .
    env_file: .env
    networks:
      - gochat-net
    ports:
      - ${WS_SERVICE_PORT}:${WS_SERVICE_PORT}
    depends_on:
      - postgres
    command: ./ws
  account:
    container_name: gochat_service_accounts
    restart: always
    build:
      dockerfile: ./platform/services/account/Dockerfile
      context: .
    env_file: .env
    networks:
      - gochat-net
    ports:
      - ${ACCOUNT_SERVICE_PORT}
    depends_on:
      - postgres
    command: ./account
  conversation:
    container_name: gochat_service_conversations
    restart: always
    build:
      dockerfile: ./platform/services/conversation/Dockerfile
      context: .
    env_file: .env
    networks:
      - gochat-net
    ports:
      - ${CONVERSATION_SERVICE_PORT}
    depends_on:
      - postgres
    command: ./conversation
  frontend:
    container_name: gochat_frontend
    restart: always
    build:
      dockerfile: ./frontend/Dockerfile
      context: .
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        REACT_APP_WS_URL: ${REACT_APP_WS_URL}
    env_file: .env
    networks:
      - gochat-net
    ports:
      - ${FRONTEND_PORT}:3000

volumes:
  pgdata: