// Code generated by go-swagger; DO NOT EDIT.

package stable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gochat/platform/endpoints/api/swagger/models"
)

// GetConversationHandlerFunc turns a function with the right signature into a get conversation handler
type GetConversationHandlerFunc func(GetConversationParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConversationHandlerFunc) Handle(params GetConversationParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetConversationHandler interface for that can handle valid get conversation params
type GetConversationHandler interface {
	Handle(GetConversationParams, *models.Principal) middleware.Responder
}

// NewGetConversation creates a new http.Handler for the get conversation operation
func NewGetConversation(ctx *middleware.Context, handler GetConversationHandler) *GetConversation {
	return &GetConversation{Context: ctx, Handler: handler}
}

/* GetConversation swagger:route GET /conversation stable getConversation

Fetches a list of conversations for a user.

*/
type GetConversation struct {
	Context *middleware.Context
	Handler GetConversationHandler
}

func (o *GetConversation) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetConversationParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
