// Code generated by go-swagger; DO NOT EDIT.

package stable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gochat/platform/endpoints/api/swagger/models"
)

// GetAccountOKCode is the HTTP code returned for type GetAccountOK
const GetAccountOKCode int = 200

/*GetAccountOK Requester's user account returned.

swagger:response getAccountOK
*/
type GetAccountOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewGetAccountOK creates GetAccountOK with default headers values
func NewGetAccountOK() *GetAccountOK {

	return &GetAccountOK{}
}

// WithPayload adds the payload to the get account o k response
func (o *GetAccountOK) WithPayload(payload *models.User) *GetAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get account o k response
func (o *GetAccountOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAccountUnauthorizedCode is the HTTP code returned for type GetAccountUnauthorized
const GetAccountUnauthorizedCode int = 401

/*GetAccountUnauthorized Unauthorized

swagger:response getAccountUnauthorized
*/
type GetAccountUnauthorized struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetAccountUnauthorized creates GetAccountUnauthorized with default headers values
func NewGetAccountUnauthorized() *GetAccountUnauthorized {

	return &GetAccountUnauthorized{}
}

// WithPayload adds the payload to the get account unauthorized response
func (o *GetAccountUnauthorized) WithPayload(payload interface{}) *GetAccountUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get account unauthorized response
func (o *GetAccountUnauthorized) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAccountUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetAccountInternalServerErrorCode is the HTTP code returned for type GetAccountInternalServerError
const GetAccountInternalServerErrorCode int = 500

/*GetAccountInternalServerError Unknown Error

swagger:response getAccountInternalServerError
*/
type GetAccountInternalServerError struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetAccountInternalServerError creates GetAccountInternalServerError with default headers values
func NewGetAccountInternalServerError() *GetAccountInternalServerError {

	return &GetAccountInternalServerError{}
}

// WithPayload adds the payload to the get account internal server error response
func (o *GetAccountInternalServerError) WithPayload(payload interface{}) *GetAccountInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get account internal server error response
func (o *GetAccountInternalServerError) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
