// Code generated by go-swagger; DO NOT EDIT.

package stable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostAuthLoginHandlerFunc turns a function with the right signature into a post auth login handler
type PostAuthLoginHandlerFunc func(PostAuthLoginParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAuthLoginHandlerFunc) Handle(params PostAuthLoginParams) middleware.Responder {
	return fn(params)
}

// PostAuthLoginHandler interface for that can handle valid post auth login params
type PostAuthLoginHandler interface {
	Handle(PostAuthLoginParams) middleware.Responder
}

// NewPostAuthLogin creates a new http.Handler for the post auth login operation
func NewPostAuthLogin(ctx *middleware.Context, handler PostAuthLoginHandler) *PostAuthLogin {
	return &PostAuthLogin{Context: ctx, Handler: handler}
}

/* PostAuthLogin swagger:route POST /auth/login stable postAuthLogin

Logs a user in and returns a JWT for secured API calls.

*/
type PostAuthLogin struct {
	Context *middleware.Context
	Handler PostAuthLoginHandler
}

func (o *PostAuthLogin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostAuthLoginParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
