// Code generated by go-swagger; DO NOT EDIT.

package stable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gochat/platform/endpoints/api/swagger/models"
)

// PostConversationHandlerFunc turns a function with the right signature into a post conversation handler
type PostConversationHandlerFunc func(PostConversationParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PostConversationHandlerFunc) Handle(params PostConversationParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PostConversationHandler interface for that can handle valid post conversation params
type PostConversationHandler interface {
	Handle(PostConversationParams, *models.Principal) middleware.Responder
}

// NewPostConversation creates a new http.Handler for the post conversation operation
func NewPostConversation(ctx *middleware.Context, handler PostConversationHandler) *PostConversation {
	return &PostConversation{Context: ctx, Handler: handler}
}

/* PostConversation swagger:route POST /conversation stable postConversation

Creates a new conversation.

*/
type PostConversation struct {
	Context *middleware.Context
	Handler PostConversationHandler
}

func (o *PostConversation) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostConversationParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
