// Code generated by go-swagger; DO NOT EDIT.

package stable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gochat/platform/endpoints/api/swagger/models"
)

// PostAuthLoginHandlerFunc turns a function with the right signature into a post auth login handler
type PostAuthLoginHandlerFunc func(PostAuthLoginParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAuthLoginHandlerFunc) Handle(params PostAuthLoginParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PostAuthLoginHandler interface for that can handle valid post auth login params
type PostAuthLoginHandler interface {
	Handle(PostAuthLoginParams, *models.Principal) middleware.Responder
}

// NewPostAuthLogin creates a new http.Handler for the post auth login operation
func NewPostAuthLogin(ctx *middleware.Context, handler PostAuthLoginHandler) *PostAuthLogin {
	return &PostAuthLogin{Context: ctx, Handler: handler}
}

/* PostAuthLogin swagger:route POST /auth/login stable postAuthLogin

Logs a user in and returns a JWT for secured API calls.

*/
type PostAuthLogin struct {
	Context *middleware.Context
	Handler PostAuthLoginHandler
}

func (o *PostAuthLogin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostAuthLoginParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
