// Code generated by go-swagger; DO NOT EDIT.

package stable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gochat/platform/endpoints/api/swagger/models"
)

// PostAccountCreatedCode is the HTTP code returned for type PostAccountCreated
const PostAccountCreatedCode int = 201

/*PostAccountCreated Account was created.

swagger:response postAccountCreated
*/
type PostAccountCreated struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewPostAccountCreated creates PostAccountCreated with default headers values
func NewPostAccountCreated() *PostAccountCreated {

	return &PostAccountCreated{}
}

// WithPayload adds the payload to the post account created response
func (o *PostAccountCreated) WithPayload(payload *models.User) *PostAccountCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post account created response
func (o *PostAccountCreated) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAccountCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAccountInternalServerErrorCode is the HTTP code returned for type PostAccountInternalServerError
const PostAccountInternalServerErrorCode int = 500

/*PostAccountInternalServerError Unknown Error

swagger:response postAccountInternalServerError
*/
type PostAccountInternalServerError struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewPostAccountInternalServerError creates PostAccountInternalServerError with default headers values
func NewPostAccountInternalServerError() *PostAccountInternalServerError {

	return &PostAccountInternalServerError{}
}

// WithPayload adds the payload to the post account internal server error response
func (o *PostAccountInternalServerError) WithPayload(payload interface{}) *PostAccountInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post account internal server error response
func (o *PostAccountInternalServerError) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
