// Code generated by go-swagger; DO NOT EDIT.

package stable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gochat/platform/endpoints/api/swagger/models"
)

// PutConversationHandlerFunc turns a function with the right signature into a put conversation handler
type PutConversationHandlerFunc func(PutConversationParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PutConversationHandlerFunc) Handle(params PutConversationParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PutConversationHandler interface for that can handle valid put conversation params
type PutConversationHandler interface {
	Handle(PutConversationParams, *models.Principal) middleware.Responder
}

// NewPutConversation creates a new http.Handler for the put conversation operation
func NewPutConversation(ctx *middleware.Context, handler PutConversationHandler) *PutConversation {
	return &PutConversation{Context: ctx, Handler: handler}
}

/* PutConversation swagger:route PUT /conversation stable putConversation

Updates an existing conversation.

*/
type PutConversation struct {
	Context *middleware.Context
	Handler PutConversationHandler
}

func (o *PutConversation) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutConversationParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
