// Code generated by go-swagger; DO NOT EDIT.

package stable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gochat/platform/endpoints/api/swagger/models"
)

// PutMessageHandlerFunc turns a function with the right signature into a put message handler
type PutMessageHandlerFunc func(PutMessageParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PutMessageHandlerFunc) Handle(params PutMessageParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PutMessageHandler interface for that can handle valid put message params
type PutMessageHandler interface {
	Handle(PutMessageParams, *models.Principal) middleware.Responder
}

// NewPutMessage creates a new http.Handler for the put message operation
func NewPutMessage(ctx *middleware.Context, handler PutMessageHandler) *PutMessage {
	return &PutMessage{Context: ctx, Handler: handler}
}

/* PutMessage swagger:route PUT /message stable putMessage

Updates an existing message.

*/
type PutMessage struct {
	Context *middleware.Context
	Handler PutMessageHandler
}

func (o *PutMessage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutMessageParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
