// Code generated by go-swagger; DO NOT EDIT.

package stable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gochat/platform/endpoints/api/swagger/models"
)

// PutAccountOKCode is the HTTP code returned for type PutAccountOK
const PutAccountOKCode int = 200

/*PutAccountOK Account was updated.

swagger:response putAccountOK
*/
type PutAccountOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewPutAccountOK creates PutAccountOK with default headers values
func NewPutAccountOK() *PutAccountOK {

	return &PutAccountOK{}
}

// WithPayload adds the payload to the put account o k response
func (o *PutAccountOK) WithPayload(payload *models.User) *PutAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put account o k response
func (o *PutAccountOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutAccountUnauthorizedCode is the HTTP code returned for type PutAccountUnauthorized
const PutAccountUnauthorizedCode int = 401

/*PutAccountUnauthorized Unauthorized

swagger:response putAccountUnauthorized
*/
type PutAccountUnauthorized struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewPutAccountUnauthorized creates PutAccountUnauthorized with default headers values
func NewPutAccountUnauthorized() *PutAccountUnauthorized {

	return &PutAccountUnauthorized{}
}

// WithPayload adds the payload to the put account unauthorized response
func (o *PutAccountUnauthorized) WithPayload(payload interface{}) *PutAccountUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put account unauthorized response
func (o *PutAccountUnauthorized) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutAccountUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PutAccountInternalServerErrorCode is the HTTP code returned for type PutAccountInternalServerError
const PutAccountInternalServerErrorCode int = 500

/*PutAccountInternalServerError Unknown Error

swagger:response putAccountInternalServerError
*/
type PutAccountInternalServerError struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewPutAccountInternalServerError creates PutAccountInternalServerError with default headers values
func NewPutAccountInternalServerError() *PutAccountInternalServerError {

	return &PutAccountInternalServerError{}
}

// WithPayload adds the payload to the put account internal server error response
func (o *PutAccountInternalServerError) WithPayload(payload interface{}) *PutAccountInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put account internal server error response
func (o *PutAccountInternalServerError) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
