// Code generated by go-swagger; DO NOT EDIT.

package stable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"gochat/platform/endpoints/api/swagger/models"
)

// PutAccountHandlerFunc turns a function with the right signature into a put account handler
type PutAccountHandlerFunc func(PutAccountParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PutAccountHandlerFunc) Handle(params PutAccountParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PutAccountHandler interface for that can handle valid put account params
type PutAccountHandler interface {
	Handle(PutAccountParams, *models.Principal) middleware.Responder
}

// NewPutAccount creates a new http.Handler for the put account operation
func NewPutAccount(ctx *middleware.Context, handler PutAccountHandler) *PutAccount {
	return &PutAccount{Context: ctx, Handler: handler}
}

/* PutAccount swagger:route PUT /account stable putAccount

Endpoint for a user to update their profile.

*/
type PutAccount struct {
	Context *middleware.Context
	Handler PutAccountHandler
}

func (o *PutAccount) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutAccountParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
