name: Push to GCP
on:
  push:
    branches:
      - 'develop'
      - 'master'
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure GCP Credentials
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
      - name: Push to GCP Artifacts Registry
        id: build-images
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build the Docker Images
          docker build -t us-central1-docker.pkg.dev/gochat-demo/gochat-service-accounts:$IMAGE_TAG us-central1-docker.pkg.dev/gochat-demo/gochat-service-accounts:${GITHUB_REF##*/} -f platform/services/account/Dockerfile .
          docker build -t us-central1-docker.pkg.dev/gochat-demo/gochat-service-conversationss:$IMAGE_TAG us-central1-docker.pkg.dev/gochat-demo/gochat-service-conversations:${GITHUB_REF##*/} -f platform/services/conversation/Dockerfile .
          docker build -t us-central1-docker.pkg.dev/gochat-demo/gochat-service-api:$IMAGE_TAG us-central1-docker.pkg.dev/gochat-demo/gochat-service-api:${GITHUB_REF##*/} -f platform/endpoints/api/Dockerfile .
          docker build -t us-central1-docker.pkg.dev/gochat-demo/gochat-service-ws:$IMAGE_TAG us-central1-docker.pkg.dev/gochat-demo/gochat-service-ws:${GITHUB_REF##*/} -f platform/endpoints/ws/Dockerfile .
          docker build -t us-central1-docker.pkg.dev/gochat-demo/gochat-service-frontend:$IMAGE_TAG us-central1-docker.pkg.dev/gochat-demo/gochat-service-frontend:${GITHUB_REF##*/} -f frontend/Dockerfile .
