name: Push to GCP
on:
  push:
    branches:
      - 'develop'
      - 'master'
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure GCP Credentials
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
      - name: Push to GCP Artifacts Registry
        id: build-images
        env:
          IMAGE_TAG: ${{ github.sha }}
          REPOSITORY_BASE: us-central1-docker.pkg.dev/gochat-demo/gochat-services
          REACT_APP_API_URL: http://localhost:8081/api/v1
          REACT_APP_WS_URL: ws://localhost:8082
        run: |
          # Build the Docker Images
          docker build -t $REPOSITORY_BASE/gochat-service-accounts:$IMAGE_TAG -t $REPOSITORY_BASE/gochat-service-accounts:${GITHUB_REF##*/} -f platform/services/account/Dockerfile .
          docker push $REPOSITORY_BASE/gochat-service-accounts --all-tags
          docker build -t $REPOSITORY_BASE/gochat-service-conversations:$IMAGE_TAG -t $REPOSITORY_BASE/gochat-service-conversations:${GITHUB_REF##*/} -f platform/services/conversation/Dockerfile .
          docker push $REPOSITORY_BASE/gochat-service-conversations --all-tags
          docker build -t $REPOSITORY_BASE/gochat-service-api:$IMAGE_TAG -t $REPOSITORY_BASE/gochat-service-api:${GITHUB_REF##*/} -f platform/endpoints/api/Dockerfile .
          docker push $REPOSITORY_BASE/gochat-service-api --all-tags
          docker build -t $REPOSITORY_BASE/gochat-service-ws:$IMAGE_TAG -t $REPOSITORY_BASE/gochat-service-ws:${GITHUB_REF##*/} -f platform/endpoints/ws/Dockerfile .
          docker push $REPOSITORY_BASE/gochat-service-ws --all-tags
          docker build -t $REPOSITORY_BASE/gochat-service-frontend:$IMAGE_TAG -t $REPOSITORY_BASE/gochat-service-frontend:${GITHUB_REF##*/} --build-arg REACT_APP_API_URL $REACT_APP_API_URL --build-arg REACT_APP_WS_URL $REACT_APP_WS_URL -f frontend/Dockerfile .
          docker push $REPOSITORY_BASE/gochat-service-frontend --all-tags
